# Generated by Django 6.0.7 on 2026-09-10 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_order_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='voucher_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Created', 'Created'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
