# Generated by Django 6.0.7 on 2026-09-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_order_voucher_error_order_voucher_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
