# Generated by Django 6.0.7 on 2026-07-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internetplan',
            name='plan_type',
        ),
        migrations.RemoveField(
            model_name='internetplan',
            name='speed',
        ),
        migrations.AddField(
            model_name='internetplan',
            name='data',
            field=models.CharField(default='10 GB', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internetplan',
            name='validity',
            field=models.CharField(default='30 Days', max_length=30),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
