# Generated by Django 6.0.7 on 2026-07-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_remove_internetplan_plan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetplan',
            name='plan_type',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly')], default='Monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='internetplan',
            name='validity',
            field=models.CharField(max_length=30),
        ),
    ]
