# Generated by Django 6.0.7 on 2026-07-31 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_internetplan_plan_type_alter_internetplan_validity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internetplan',
            options={'ordering': ['display_order', 'price']},
        ),
        migrations.AddField(
            model_name='internetplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='internetplan',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.'),
        ),
        migrations.AddField(
            model_name='internetplan',
            name='popular',
            field=models.BooleanField(default=False, help_text="Show 'Most Popular' badge on this plan."),
        ),
    ]
