# Generated by Django 6.0.7 on 2026-09-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_internetplan_options_internetplan_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internetplan',
            name='unlimited',
            field=models.BooleanField(default=False, help_text='Allow unlimited data usage for this plan.'),
        ),
    ]
