# Generated by Django 6.0.7 on 2026-09-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_internetplan_unlimited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internetplan',
            name='unlimited',
        ),
    ]
