# Generated by Django 6.0.7 on 2026-07-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_internetplan_customer_data_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='customer',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='is_active',
            new_name='active_plan',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='data_balance',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='device_mac',
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.DeleteModel(
            name='InternetPlan',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
