# Generated by Django 6.0.7 on 2026-07-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_remove_subscription_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='plan_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='plan_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
