# Generated by Django 6.0.7 on 2026-07-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customer_plan_expiry_customer_plan_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='data_balance',
            field=models.CharField(default='0 GB', max_length=30),
        ),
    ]
