# Generated by Django 6.0.7 on 2026-07-25 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customer_data_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='hotspot_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='hotspot_username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
