# Generated by Django 6.0.7 on 2026-07-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_customer_hotspot_password_customer_hotspot_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='telegram_code',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
