# Generated by Django 6.0.7 on 2026-07-30 13:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_telegram_code_customer_telegram_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='telegram_code',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=50, unique=True)),
                ('ip_address', models.CharField(blank=True, max_length=50)),
                ('connected', models.BooleanField(default=False)),
                ('data_used', models.CharField(default='0 GB', max_length=30)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='customers.customer')),
            ],
        ),
    ]
