# Generated by Django 6.0.7 on 2026-08-05 13:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customer_telegram_code_device'),
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='data_used',
        ),
        migrations.AddField(
            model_name='device',
            name='first_connected',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.voucher'),
        ),
        migrations.AlterField(
            model_name='device',
            name='connected',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='device_name',
            field=models.CharField(blank=True, default='Unknown Device', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='mac_address',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
