# Generated by Django 6.0.7 on 2026-08-06 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_remove_device_data_used_device_first_connected_and_more'),
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='data_used',
            field=models.CharField(default='0 MB', max_length=30),
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('data_used', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='customers.device')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vouchers.voucher')),
            ],
        ),
    ]
