# Generated by Django 6.0.7 on 2026-08-05 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0008_alter_customer_telegram_code_device'),
        ('payments', '0002_alter_order_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_code', models.CharField(max_length=50, unique=True)),
                ('plan_name', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=50)),
                ('device_limit', models.PositiveIntegerField(default=2)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Used', 'Used'), ('Expired', 'Expired')], default='Active', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='customers.customer')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voucher', to='payments.order')),
            ],
        ),
    ]
